apiVersion: v2
name: kube-prometheus-stack
type: application

version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: '58.7.2'
    repository: 'https://prometheus-community.github.io/helm-charts'

